import 'package:flutter/material.dart';

class Doctor {
  static final getData = [
    {
      'id': 0,
      'name': "Dr. Ashok K",
      'category': "Cardiologist",
      'score': "3.5",
      'reviewCount': "135",
      'photo': 'images/ashok.jpg',
      'gmail': 'drashokk@gmail.com',
      'Address': 'No.2, 2/382 2nd Street, Porur, Chennai',
      'Place': 'Chennai',
      'working': 'Mon-Fri 8:00AM - 4:00PM',
    },
    {
      'id': 1,
      'name': "Dr. Antony Vishal Y S",
      'category': "Psychiatrist",
      'score': "5.0",
      'reviewCount': "12",
      'photo': 'images/Antony.jpg',
      'gmail': 'antonyvishal.antony@gmail.com',
      'Address': 'Malar Hospital, Main Block, Chennai',
      'Place': 'Chennai',
      'working': 'Mon-Wed 12:00PM - 3:00PM',
    },
    {
      'id': 2,
      'name': "Dr. John",
      'category': "Neurology",
      'score': "4.0",
      'reviewCount': "171",
      'photo': 'images/john.jpg',
      'gmail': 'johncena@gmail.com',
      'Address': 'Ramachandra Hospital, Porur, Kerala',
      'Place': 'Kerala',
      'working': 'Mon-Fri 4:00PM - 9:00PM',
    },
    {
      'id': 3,
      'name': "Dr. Priya R",
      'category': "Dentist",
      'score': "4.8",
      'reviewCount': "257",
      'photo': 'images/priya.jpg',
      'gmail': 'drpriya@gmail.com',
      'Address': 'No.9, West Street, Ashok Nagar, Madurai',
      'Place': 'Madurai',
      'working': 'Mon-Fri 8:00AM - 4:00PM',
    },
    {
      'id': 4,
      'name': "Dr. Subashini T",
      'category': "Gynaecologist",
      'score': "5.0",
      'reviewCount': "45",
      'photo': 'images/subhashini.jpg',
      'gmail': 'subashinit@gmail.com',
      'Address': 'No.21/53, First Floor, Malar Apartments, Vadapalani, Chennai',
      'Place': 'Chennai',
      'working': 'Mon & Wed 10:00AM - 2:00PM',
    },
    {
      'id': 5,
      'name': "Dr. Ram Prasad",
      'category': "Pulmonologist",
      'score': "2,7",
      'reviewCount': "118",
      'photo': 'images/ramPrasad.jpg',
      'gmail': 'ramprasad@gmail.com',
      'Address': 'Raj Hospital, Raj Road, Bangalore',
      'Place': 'Bangalore',
      'working': 'Mon-Fri 8:00AM - 4:00PM',
    },
  ];
}
